# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
  title: Lauri Lemmenlehti
  baseurl: "/lemmenlehti" # the subpath of your site, e.g. /blog
  url: "" # the base hostname & protocol for your site
  permalink: # /:categories/:title/
  description: > # this means to ignore newlines until "baseurl:"
    Personal Website for Lauri Lemmenlehti.
  author:
      name: "Lauri Lemmenlehti"
      email: "lauri.lemmenlehti@gmail.com"
      website: ""
      twitter: "@lemmenlehti"
      github: "lemmenlehti"
  img: /assets/
  #lastmod: 2015-04-15T23:12:14+05:30

  # Build settings
  markdown: kramdown

  sass:
      sass_dir: _sass
      style: :compressed
